# Script-mode helper invoked from release/CMakeLists.txt.
#
# Walks the given Windows PE files via file(GET_RUNTIME_DEPENDENCIES) and writes
# an Inno Setup fragment with a [Files] entry for every non-system DLL found.
#
# Inputs (set via cmake -D...):
#   BINARIES   ';'-separated list of executables/DLLs to scan
#   DIRECTORIES  ';'-separated list of search directories (typically the mingw bin dir)
#   OUTPUT     full path of the .iss fragment to (re)write
#   COMPONENT  optional Inno Setup component name to attach to each Source line
#
# Output: a file at ${OUTPUT} containing one Source: line per resolved DLL.
# Existing copies are overwritten.

if(NOT BINARIES OR NOT OUTPUT)
  message(FATAL_ERROR "collect_runtime_deps.cmake: BINARIES and OUTPUT are required")
endif()

# System DLLs we never want to bundle. The Windows loader resolves these.
set(_post_exclude
  "[/\\\\][Ss]ystem32[/\\\\]"
  "[/\\\\]SysWOW64[/\\\\]"
  "[/\\\\]WinSxS[/\\\\]"
)

set(_pre_exclude
  "^api-ms-"
  "^ext-ms-"
  "^[Kk]ernel32\\.dll$"
  "^[Uu]ser32\\.dll$"
  "^[Aa]dvapi32\\.dll$"
  "^[Ww]s2_32\\.dll$"
  "^[Cc]rypt32\\.dll$"
  "^[Bb]crypt\\.dll$"
  "^[Nn]crypt\\.dll$"
  "^[Gg]di32\\.dll$"
  "^[Ss]hell32\\.dll$"
  "^[Cc]omctl32\\.dll$"
  "^[Cc]omdlg32\\.dll$"
  "^[Oo]le32\\.dll$"
  "^[Oo]leaut32\\.dll$"
  "^[Mm]simg32\\.dll$"
  "^[Ww]inmm\\.dll$"
  "^[Mm]svcrt\\.dll$"
  "^[Ii]mm32\\.dll$"
  "^[Ss]etupapi\\.dll$"
  "^[Ss]ecur32\\.dll$"
  "^[Dd]wmapi\\.dll$"
  "^[Uu]xtheme\\.dll$"
  "^[Vv]ersion\\.dll$"
  "^[Mm]fplat\\.dll$"
  "^[Mm]fuuid\\.dll$"
  "^[Ww]mcodecdspuuid\\.dll$"
  "^d3d.*\\.dll$"
  "^dxgi\\.dll$"
  "^hid\\.dll$"
)

file(GET_RUNTIME_DEPENDENCIES
  EXECUTABLES ${BINARIES}
  RESOLVED_DEPENDENCIES_VAR _resolved
  UNRESOLVED_DEPENDENCIES_VAR _unresolved
  DIRECTORIES ${DIRECTORIES}
  PRE_EXCLUDE_REGEXES ${_pre_exclude}
  POST_EXCLUDE_REGEXES ${_post_exclude}
)

list(REMOVE_DUPLICATES _resolved)
list(SORT _resolved CASE INSENSITIVE)

set(_extra "")
if(COMPONENT)
  set(_extra "; Components: ${COMPONENT}")
endif()

set(_lines "; Auto-generated by collect_runtime_deps.cmake -- do not edit.\n")
foreach(_dll IN LISTS _resolved)
  file(TO_NATIVE_PATH "${_dll}" _native)
  string(APPEND _lines "Source: \"${_native}\"; DestDir: \"{app}\"; Flags: ignoreversion${_extra}\n")
endforeach()

file(WRITE "${OUTPUT}" "${_lines}")

if(_unresolved)
  message(STATUS "collect_runtime_deps: ${OUTPUT} written, but some deps were unresolved:")
  foreach(_u IN LISTS _unresolved)
    message(STATUS "  unresolved: ${_u}")
  endforeach()
else()
  message(STATUS "collect_runtime_deps: wrote ${OUTPUT}")
endif()
